workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "sefra.kr"
        APP_STORE_APPLE_ID: 6754912654
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter build
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Setup iOS Entitlements
        script: |
          # Add entitlements to Xcode project using PlistBuddy
          /usr/libexec/PlistBuddy -c "Add :CODE_SIGN_ENTITLEMENTS string Runner/Runner.entitlements" ios/Runner.xcodeproj/project.pbxproj || true

          # Ensure Runner.entitlements exists
          if [ ! -f ios/Runner/Runner.entitlements ]; then
            cat > ios/Runner/Runner.entitlements << 'ENTITLEMENTS'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>aps-environment</key>
            <string>production</string>
          </dict>
          </plist>
          ENTITLEMENTS
          fi
      - name: Clean and update pods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build iOS release with Xcode (skip Flutter build)
        script: |
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/ios/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/ios/Runner.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist $CM_BUILD_DIR/ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - zanoone2@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
