workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "sefra.kr"
        APP_STORE_APPLE_ID: 6754912654
        GOOGLE_SERVICE_INFO_PLIST: Encrypted(...) # Add in Codemagic UI: Environment variables
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Firebase configuration
        script: |
          echo "$GOOGLE_SERVICE_INFO_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Clean and update pods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - zanoone2@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
