workflows:
  ios-release:
    name: Sefra iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: sefra.kr
      vars:
        XCODE_WORKSPACE: "Sefra/Sefra.xcworkspace"
        XCODE_SCHEME: "Sefra"
        BUNDLE_ID: "sefra.kr"
        APP_STORE_APPLE_ID: 6754912654
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd Sefra
          pod install --repo-update
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Verify iOS Entitlements
        script: |
          # Verify Sefra.entitlements exists
          if [ ! -f Sefra/Sefra/Sefra.entitlements ]; then
            echo "⚠️ Warning: Sefra.entitlements not found!"
            exit 1
          else
            echo "✅ Sefra.entitlements found"
            cat Sefra/Sefra/Sefra.entitlements
          fi
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Release" \
            --export-options-plist "Sefra/exportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - zanoone2@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  ios-debug:
    name: Sefra iOS Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: sefra.kr
      vars:
        XCODE_WORKSPACE: "Sefra/Sefra.xcworkspace"
        XCODE_SCHEME: "Sefra"
        BUNDLE_ID: "sefra.kr"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd Sefra
          pod install --repo-update
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for development
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config "Debug" \
            --export-options-plist "Sefra/exportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - zanoone2@gmail.com
        notify:
          success: true
          failure: true
